site_name: OSG Security
site_url: https://opensciencegrid.org/security/
repo_url: https://github.com/opensciencegrid/security/
theme: 
  name: material
  custom_dir: osgthedocs

pages:
- Home: 'index.md'
- Security Team: 'SecurityTeamMembers.md'
- Security Announcements:
  - Overview: 'OSGSecurityAnnouncements.md'
  - Overview x86 vulnerabilities: 'OSGSecurityAnnouncements-x86.md'
  - Announcement Details:
    - OSG-SEC-2020-08-31 Vulnerabilities in frontier-squid: 'vulns/OSG-SEC-2020-08-31-Vulnerabilities-in-frontier-squid.md'
    - OSG-SEC-2020-05-05 Singularity and unprivileged user namespaces: 'vulns/OSG-SEC-2020-05-05-Singularity-and-unprivileged-user-namespaces.md'
    - OSG-SEC-2020-03-26 Vulnerability in xrootd-scitokens Plugin: 'vulns/OSG-SEC-2020-03-26-Vulnerability-in-xrootd-scitokens-plugin.md'
    - OSG-SEC-2020-02-07 Vulnerabilities in Frontier Squid: 'vulns/OSG-SEC-2020-02-07-Vulnerabilities-in-frontier-squid.md'
    - OSG-SEC-2019-11-15 Vulnerability in Squid UPDATE 2: 'vulns/OSG-SEC-2019-11-15-Vulnerability-in-Squid-UPDATE-2.md'
    - OSG-SEC-2019-11-11 Vulnerability in Squid UPDATE: 'vulns/OSG-SEC-2019-11-11-Vulnerability-in-Squid-UPDATE.md'
    - OSG-SEC-2019-11-08 Vulnerability in Squid: 'vulns/OSG-SEC-2019-11-08-Vulnerability-in-Squid.md'
    - OSG-SEC-2019-07-25 Vulnerability in Squid: 'vulns/OSG-SEC-2019-07-25-Vulnerability-in-Squid.md'
    - OSG-SEC-2019-05-14 Vulnerability in Singularity: 'vulns/OSG-SEC-2019-05-14-Vulnerability-in-Singularity.md'
    - OSG-SEC-2018-12-12 Critical vulnerability in Singularity Update 2: 'vulns/OSG-SEC-2018-12-12-Critical-vulnerability-in-Singularity-Update-2.md'
    - OSG-SEC-2018-12-12 Critical vulnerability in Singularity Update: 'vulns/OSG-SEC-2018-12-12-Critical-vulnerability-in-Singularity-Update.md'
    - OSG-SEC-2018-12-12 Critical vulnerability in Singularity: 'vulns/OSG-SEC-2018-12-12-Critical-vulnerability-in-Singularity.md'
    - OSG-SEC-2018-10-18 Vulnerability in Linux kernel’s create_elf_tables() function Update: 'vulns/OSG-SEC-2018-10-18-Vulnerability-in-Linux-kernel-Update.md'
    - OSG-SEC-2018-10-04 Vulnerability in RedHat Ceph Storage: 'vulns/OSG-SEC-2018-10-04-Vulnerability-in-Red-Hat-Ceph-Storage.md'
    - OSG-SEC-2018-10-02 Vulnerability in Linux kernel’s create_elf_tables() function: 'vulns/OSG-SEC-2018-10-02-Vulnerability-in-Linux-kernel.md'
    - OSG-SEC-2018-09-20 Vulnerability in AFS: 'vulns/OSG-SEC-2018-09-20-Vulnerabilities-in-AFS.md'
    - OSG-SEC-2018-09-06 Vulnerability in Apache Struts: 'vulns/OSG-SEC-2018-09-06-Apache-Struts-Vulnerability.md' 
    - OSG-SEC-2018-08-17 Foreshadow: 'vulns/OSG-SEC-2018-08-17-Foreshadow.md'
    - OSG-SEC-2018-08-07 Data channel encryption not guaranteed: 'vulns/OSG-SEC-2018-08-07-data-channel-encryption-not-guaranteed.md'
    - OSG-SEC-2018-07-05 Vulnerabilities in Singularity: 'vulns/OSG-SEC-2018-07-05-Singularity-Vulnerabilities.md'
    - OSG-SEC-2018-07-03 BLAHP vulnerability: 'vulns/OSG-SEC-2018-07-03-BLAHP-Vulnerability.md'
    - OSG-SEC-2018-05-23 CILogon OSG CA service retirement: 'vulns/OSG-SEC-2018-05-23-OSG-CA-service-retirement.md'
    - OSG-SEC-2018-05-18 Multiple EL7 Linux kernel vulnerabilities: 'vulns/OSG-SEC-2018-05-18-Multiple-EL7-Linux-kernel-vulnerabilities.md'
    - OSG-SEC-2018-05-08 Meltdown-Spectre Update: 'vulns/OSG-SEC-2018-05-08-Meltdown-Spectre-Update.md'
    - OSG-SEC-2018-05-07 Unprivileged user namespaces in Singularity: 'vulns/OSG-SEC-2018-05-07-Unprivileged-User-Namespaces-vulnerability.md'
    - OSG-SEC-2018-04-30 Multiple vulnerabilities in Singularity: 'vulns/OSG-SEC-2018-04-30-Multiple-Singularity-Vulnerabilities.md'
    - OSG-SEC-2018-04-25 Including Let’s Encrypt CA in the OSG CA bundle: 'vulns/OSG-SEC-2018-04-25-Including-Lets-Encrypt-in-OSG-CA-bundle.md'
    - OSG-SEC-2018-04-19 Critical vulnerability in Singularity Update: 'vulns/OSG-SEC-2018-04-19-Critical-Vulnerability-in-Singularity-Update.md'
    - OSG-SEC-2018-04-17 Vulnerability in MariaDB MySQL: 'vulns/OSG-SEC-2018-04-17-Vulnerability-in-MariaDB-MySQL.md'
    - OSG-SEC-2018-04-02 Critical vulnerability in Singularity: 'vulns/OSG-SEC-2018-04-02-Critical-Vulnerability-in-Singularity.md'
    - OSG-SEC-2018-03-27 Vulnerability in SLURM: 'vulns/OSG-SEC-2018-03-27-SLURM-Vulnerability.md'
    - OSG-SEC-2018-03-13 SAML Vulnerabilities affecting multiple implementations: 'vulns/OSG-SEC-2018-03-13-SAML-Vulnerabilities-affecting-multiple-implementations.md'
    - OSG-SEC-2018-03-08 Limiting Singularity image types: 'vulns/OSG-SEC-2018-03-08-Limiting-Singularity-image-types.md'
    - OSG-SEC-2018-03-05 Vulnerability in Singularity: 'vulns/OSG-SEC-2018-03-05-Singularity-Vulnerability.md'
    - OSG-SEC-2018-02-28 Disable weak ciphers in SSL: 'vulns/OSG-SEC-2018-02-28-Weak-SSL-ciphers.md'
    - OSG-SEC-2018-01-22 Meltdown-Spectre Update: 'vulns/OSG-SEC-2018-01-22-Meltdown-Spectre-Update.md'
    - OSG-SEC-2018-01-10 Meltdown-Spectre Update: 'vulns/OSG-SEC-2018-01-10-Meltdown-Spectre-Update.md'
    - OSG-SEC-2018-01-04 Meltdown-Spectre Update: 'vulns/OSG-SEC-2018-01-04-Meltdown-Spectre.md'
- CILogon OSG CA:
  - CILogon OSG CA: 'OSGCertificateService.md'
  - Frequently Asked Questions (FAQ): 'CILogonOSGFAQ.md'
- Certificate Authorities (CA) Distribution: 'CaDistribution.md'
- OSG Security Policies & Procedures:
  - Including Let’s Encrypt signing certificate in OSG CA bundle: 'LetsEncryptOSGCAbundle.md'
  - Approved OSG Security Policies: 'OSGSecurityPolicies.md'
  - Site/VO Removal Policy: 'SiteVORemovalPolicy.md'
  - OSG Security Procedures: 'OSGSecurityProcedures.md'
  - Site/VO Removal Procedure: 'SiteVORemovalProcedure.md'
  - Secure Communications in OSG: 'SecureCommunicationsOSG.md'
  - Software Vulnerability Handling: 'SoftwareVulnerabilityHandling.md'
  - Incident Discovery Reporting: 'IncidentDiscoveryReporting.md'
  - Joining Security-SIG mailing list: 'fnal-mail-list-join.md'
- Integrated Security for the OSG:
  - Security Awareness for the OSG: 'SecurityAwarenessForTheOSG.md'
  - Security User Responsibilities: 'SecurityUserResponsibilities.md'
  - Security Site Responsibilities: 'SecuritySiteResponsibilities.md'

markdown_extensions:
  - admonition
  - osg_markdown.colors

