name: Deploy static MkDocs pages
on:
  push:
    branches: [ master ]

jobs:
  deploy-mkdocs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Deploy MkDocs pages
        if: startsWith(github.repository, 'opensciencegrid/')
        uses: docker://squidfunk/mkdocs-material:7.1.0
        with:
          args: >-
            gh-deploy
            --verbose
